ktor:
  application:
    modules:
      - com.bltucker.recipemanager.ApplicationKt.module
  deployment:
    port: 8080
    host: 0.0.0.0

database:
  url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/recipemanager_dev}
  driver: org.postgresql.Driver
  maxPoolSize: ${DATABASE_MAX_POOL_SIZE:10}

app:
  environment: ${APP_ENV:dev}
  jwtSecret: ${JWT_SECRET:dev-secret-key-change-in-prod}