name: Run Gradle Tests

on:
  pull_request:
    branches: [ master ] # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests with Gradle
        # Continue on error so the next steps can publish test results
        continue-on-error: true
        run: ./gradlew test

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        if: always() # This ensures that results are uploaded even if tests fail
        with:
          name: test-results
          path: build/test-results/test/

      - name: Publish Test Summary
        uses: dorny/test-reporter@v1
        if: always() # Run this step even if the tests fail
        with:
          name: JUnit Test Report
          path: "build/test-results/test/*.xml"
          reporter: java-junit